export { default as Views } from './Views';
export { default as Anexos } from './Anexos';
export { default as Estados } from './Estados';
export { default as Versoes } from './Versoes';
export { InfoCon, InfoCredito } from './info-extra';
export { default as Transicoes } from './Transicoes';
export { default as DadosGerais } from './DadosGerais';
export { default as TodosAnexos } from './todos-anexos';
export { default as NotaProcesso } from './NotaProcesso';
export { default as TableDetalhes } from './TableDetalhes';
export { default as DetalhesProcesso } from './DetalhesProcesso';
export { default as Pareceres, PareceresEstado } from './Pareceres';
