export { default as Views } from './Views';
export { default as Anexos } from './Anexos';
export { default as Versoes } from './Versoes';
export { default as Pareceres } from './Pareceres';
export { default as Transicoes } from './Transicoes';
export { default as DadosGerais } from './DadosGerais';
export { default as NotaProcesso } from './NotaProcesso';
export { default as TableDetalhes } from './TableDetalhes';
export { default as DetalhesProcesso } from './DetalhesProcesso';
